/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerationsIndexRouteImport } from './routes/generations/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as GenerationsGenerationIdRouteImport } from './routes/generations/$generationId'
import { Route as DashboardIdRouteImport } from './routes/dashboard/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsIndexRoute = GenerationsIndexRouteImport.update({
  id: '/generations/',
  path: '/generations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsGenerationIdRoute = GenerationsGenerationIdRouteImport.update({
  id: '/generations/$generationId',
  path: '/generations/$generationId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/generations/$generationId': typeof GenerationsGenerationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/generations/': typeof GenerationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/generations/$generationId': typeof GenerationsGenerationIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/generations': typeof GenerationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/generations/$generationId': typeof GenerationsGenerationIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/generations/': typeof GenerationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/$id'
    | '/generations/$generationId'
    | '/dashboard/'
    | '/generations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/$id'
    | '/generations/$generationId'
    | '/dashboard'
    | '/generations'
  id:
    | '__root__'
    | '/'
    | '/dashboard/$id'
    | '/generations/$generationId'
    | '/dashboard/'
    | '/generations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIdRoute: typeof DashboardIdRoute
  GenerationsGenerationIdRoute: typeof GenerationsGenerationIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  GenerationsIndexRoute: typeof GenerationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/': {
      id: '/generations/'
      path: '/generations'
      fullPath: '/generations/'
      preLoaderRoute: typeof GenerationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/$generationId': {
      id: '/generations/$generationId'
      path: '/generations/$generationId'
      fullPath: '/generations/$generationId'
      preLoaderRoute: typeof GenerationsGenerationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIdRoute: DashboardIdRoute,
  GenerationsGenerationIdRoute: GenerationsGenerationIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  GenerationsIndexRoute: GenerationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
