/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerationsIndexRouteImport } from './routes/generations/index'
import { Route as GenerationsGenerationIdRouteImport } from './routes/generations/$generationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsIndexRoute = GenerationsIndexRouteImport.update({
  id: '/generations/',
  path: '/generations/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsGenerationIdRoute = GenerationsGenerationIdRouteImport.update({
  id: '/generations/$generationId',
  path: '/generations/$generationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/login': typeof LoginRoute
  '/generations/$generationId': typeof GenerationsGenerationIdRoute
  '/generations/': typeof GenerationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/login': typeof LoginRoute
  '/generations/$generationId': typeof GenerationsGenerationIdRoute
  '/generations': typeof GenerationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/login': typeof LoginRoute
  '/generations/$generationId': typeof GenerationsGenerationIdRoute
  '/generations/': typeof GenerationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/login'
    | '/generations/$generationId'
    | '/generations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$id' | '/login' | '/generations/$generationId' | '/generations'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/login'
    | '/generations/$generationId'
    | '/generations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  LoginRoute: typeof LoginRoute
  GenerationsGenerationIdRoute: typeof GenerationsGenerationIdRoute
  GenerationsIndexRoute: typeof GenerationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/': {
      id: '/generations/'
      path: '/generations'
      fullPath: '/generations/'
      preLoaderRoute: typeof GenerationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/$generationId': {
      id: '/generations/$generationId'
      path: '/generations/$generationId'
      fullPath: '/generations/$generationId'
      preLoaderRoute: typeof GenerationsGenerationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  LoginRoute: LoginRoute,
  GenerationsGenerationIdRoute: GenerationsGenerationIdRoute,
  GenerationsIndexRoute: GenerationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
